name: Go package

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:

      # action文档
      # https://github.com/marketplace/actions/setup-tidb
      - uses: Icemap/tidb-action@v1.0
        with:
          port: 4001 # Optional, default is 4000, the port on which TiDB will run
          version: "v6.1.0" # Optional, default is v6.2.0, the version TiDB is running
          config: |
            [tikv-client.async-commit]
            safe-window = 0
            allowed-clock-drift = 0 # Optional, default is empty, if you need special TiDB configuration, write the configuration here
          inner port: 4000 # Optional, defaults to 4000, refers port inside the TiDB container, which is a configuration that is only used if you change the port in the config param

      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Test
        run: go test -v ./...
        env:
          STORAGE_LOCK_TIDB_DSN: "root:@tcp(127.0.0.1:4000)/storage_lock_test"